DROP TABLE IF EXISTS COMPETITOR;

CREATE TABLE COMPETITOR(ID INT AUTO_INCREMENT, START_POS INT, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), SPLIT_TIME INT DEFAULT 0, FINISH_TIME INT DEFAULT 0);

INSERT INTO COMPETITOR(START_POS, FIRSTNAME, LASTNAME) VALUES (1, 'Tyrell', 'Raleigh');
INSERT INTO COMPETITOR(START_POS, FIRSTNAME, LASTNAME) VALUES (2, 'Kaden', 'Chase');
INSERT INTO COMPETITOR(START_POS, FIRSTNAME, LASTNAME) VALUES (3, 'Edgar', 'Arthur');
INSERT INTO COMPETITOR(START_POS, FIRSTNAME, LASTNAME) VALUES (4, 'Bailey', 'Hewie');
INSERT INTO COMPETITOR(START_POS, FIRSTNAME, LASTNAME) VALUES (5, 'Dwayne', 'Johnnie');
INSERT INTO COMPETITOR(START_POS, FIRSTNAME, LASTNAME) VALUES (6, 'Junior', 'Moss');
INSERT INTO COMPETITOR(START_POS, FIRSTNAME, LASTNAME) VALUES (7, 'Terrance', 'Mark');
INSERT INTO COMPETITOR(START_POS, FIRSTNAME, LASTNAME) VALUES (8, 'Isaiah', 'Billie');
INSERT INTO COMPETITOR(START_POS, FIRSTNAME, LASTNAME, SPLIT_TIME, FINISH_TIME) VALUES (8, 'Brion', 'Headley', 15000, 20000);
